modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/Lance5057/ExtraDelight/issues"

[[mods]]
	modId = "extradelight"
	version="${file.jarVersion}"
	displayName = "ExtraDelight"
	displayURL = "https://github.com/Lance5057/ExtraDelight"
	credits = "Alan199921, DivineAspect, Skysom, FreneticScribbler, Lanse505, Belathus, RoyalJelly"
	authors = "Lance5057"

[[dependencies.extradelight]]
    modId = "farmersdelight"
    mandatory = true
    versionRange = "[1.2.0,)"
    ordering = "AFTER"
    side = "BOTH"